# Generated by Django 4.1.7 on 2023-05-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='Nombre Corto')),
                ('anulate', models.BooleanField(default=False, verbose_name='Anulado')),
            ],
            options={
                'verbose_name': 'Mi departamento',
                'verbose_name_plural': 'Areas de la empresa',
                'ordering': ['name'],
                'unique_together': {('name', 'short_name')},
            },
        ),
    ]
